### ISSUE TITLE
Hey rupert its jim

### ISSUE THREAD

**Issue by ilovedollssomuch** [Coadon/getaway#1]
hello dude! Cant contact you anymore on microsoft teams. Had a thought one day i might keep working on this. Can you share the project somehow? also i would like to get a contact option from you thanks.

**Comment by Coadon** [comment]
Long time no see my dude. Thanks for opening an issue for your take on maintaining this game.

It is considerable to post all of Getaway's source files here and turn them into an open-source project, cause you couldn't turn a repo closed source if it had a GitHub page running. Directly sharing the source tree is not practical, and I rather not do that. I don't actually have any sort of version control (git) originally hooked with the tree, so if we do, the commit history has to start clean. (which is fine, I suppose.)

My reason for dropping maintenance on this game isn't _entirely_ because I don't have ideas (tbh I don't know how to make a map). The other reason is that I uninstalled Unity and I no longer own a license for it. We could talk about this more.

How you envision the design of this game? Where would you consider grabbing art resources from? And how confident are you willing to take on the swarn of bugs? This is _not_ a qualification whatsoever, im just asking for your thoughts.

The game's source tree is presently stored inside a backup disk. I'll have to dust it out if we wanna work on it, and that takes a little time.

You may contact me via Discord on @fortpile. Pls add friend, I don't know your usrname.

**Comment by ilovedollssomuch** [comment]
my username is ilovedollssomuch. when adding you on discord, it says u dont accept friend invites. u can add me using my username.

**Comment by Coadon** [comment]
Oh right yeh. I disabled friend invites cuz there were random strangers friending me.

Request sent.
